- .gitmessage
- README.md
- pull_request_template.md
I've decided to keep it in a single file for now. We can add `CONTRIBUTING.md` later on
> [doc] (root) contribution and templates

- packages/payments-common/src/BasePayments.ts
The change is needed to dynamically identify if sweep is possible based on real time transaction costs
> [feat] (common) isSweepable boolean or Promise<boolean>

- packages/ethereum-payments/src/BaseEthereumPayments.ts
> [fix] (ethereum) marking eth transactions as failed

- packages/ethereum-payments/package-lock.json
- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/test/HdEthereumPayments.test.ts
Return current block number with ethereum's tx info
> [feature] (ethereum) block number in TxInfo

- packages/ethereum-payments/package-lock.json
- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/constants.ts
- packages/ethereum-payments/src/types.ts
- packages/ethereum-payments/test/HdEthereumPayments.test.ts
- packages/ethereum-payments/test/NetworkData.test.ts
- packages/ethereum-payments/test/end-to-end.test.ts
* use 21052 units of gas instead of 21000
> [feat] (ethereum) extra gas for error

- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/NetworkData.ts
- packages/ethereum-payments/src/constants.ts
- packages/ethereum-payments/test/HdEthereumPayments.test.ts
- packages/ethereum-payments/test/NetworkData.test.ts
- packages/ethereum-payments/test/end-to-end.test.ts
- packages/ethereum-payments/test/fixtures/mocks.ts
Tested with both normal and txs stuck due to low fee
> [feat] (ethereum) always estimate fee with web3

- packages/ethereum-payments/src/NetworkData.ts
> [fix] (ethereum) round gas after multiplying

- packages/payments-common/src/BasePayments.ts
> [feat] (common) accept address as source of sweep

- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/HdEthereumPayments.ts
- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
- packages/ethereum-payments/src/erc20/HdErc20Payments.ts
- packages/ethereum-payments/src/types.ts
- packages/ethereum-payments/test/EthereumPaymentsFactory.test.ts
- packages/ethereum-payments/test/HdEthereumPayments.test.ts
- packages/ethereum-payments/test/erc20/end-to-end.test.ts
> [feat](ethereum) add support for service tx

- packages/ethereum-payments/src/NetworkData.ts
> [feat](ethereum|erc20) gasStation api key support

- packages/ethereum-payments/package-lock.json
- packages/ethereum-payments/package.json
> [fix] (ethereum) remove bip32 stub types package

- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
> [fix](erc20) allow sweep out tx signature

- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
> [fix](erc20) convert all fee values to fixed

- packages/bitcoin-payments/src/MultisigBitcoinPayments.ts
- packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
- packages/bitcoin-payments/src/bitcoinish/types.ts
- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/litecoin-payments/src/BaseLitecoinPayments.ts
- packages/payments-common/src/BasePayments.ts
- packages/payments-common/src/types.ts
- packages/ripple-payments/src/BaseRipplePayments.ts
- packages/stellar-payments/src/BaseStellarPayments.ts
- packages/tron-payments/src/BaseTronPayments.ts
> [feat](all) add mock for creation of multioutput tx

- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
Also refactor a few local variables for clarity
> [fix] (ethereum) Improve insufficient ETH balance for ERC20 transactions

- packages/coin-payments/package-lock.json
- packages/coin-payments/package.json
- packages/coin-payments/src/constants.ts
- packages/coin-payments/src/index.ts
- packages/coin-payments/src/types.ts
- packages/coin-payments/test/CoinPayments.test.ts
> [fix] (litecoin) ltc coin-payments, install @faast/litecoin-payments

- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
The ERC20 spec allows tokens to do one of two things on failure:
1. revert the transaction
2. return false
Our implementation already handles the first case by setting the `isUnexecuted` flag to `true`. However the other case isn't currently handled. The most universal way to confirm a successful transfer is to look for the `Transfer` event. This PR fixes `getTransactionInfo` handling of failure case 2 as well as catches cases where a mismatched amount was transferred.
> [fix] (ethereum) Handle erc20 transfer failure edge case

- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
> [feat](erc20|eth) fix destination of legacy sweep

- packages/bitcoin-cash-payments/src/BitcoinCashPaymentsUtils.ts
> Bch fee fix

- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/EthereumPaymentsUtils.ts
- packages/ethereum-payments/src/KeyPairEthereumPayments.ts
- packages/ethereum-payments/src/bip44.ts
- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
- packages/ethereum-payments/src/erc20/HdErc20Payments.ts
- packages/ethereum-payments/test/EthereumPaymentsFactory.test.ts
- packages/ethereum-payments/test/EthereumPaymentsUtils.test.ts
- packages/ethereum-payments/test/HdEthereumPayments.test.ts
- packages/ethereum-payments/test/KeyPairEthereumPayments.test.ts
- packages/ethereum-payments/test/NetworkData.test.ts
- packages/ethereum-payments/test/bip44.test.ts
- packages/ethereum-payments/test/erc20/end-to-end.test.ts
> [feat](eth|erc20) force return lowercase addresses

- package.json
- packages/bitcoin-cash-payments/package-lock.json
- packages/bitcoin-cash-payments/package.json
- packages/bitcoin-payments/package-lock.json
- packages/bitcoin-payments/package.json
- packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
- packages/bitcoin-payments/test/e2e.mainnet.test.ts
- packages/coin-payments/package-lock.json
- packages/coin-payments/package.json
- packages/ethereum-payments/package-lock.json
- packages/ethereum-payments/package.json
- packages/litecoin-payments/package-lock.json
- packages/litecoin-payments/package.json
- packages/payments-common/package-lock.json
- packages/payments-common/package.json
- packages/payments-common/src/types.ts
- packages/ripple-payments/package-lock.json
- packages/ripple-payments/package.json
- packages/stellar-payments/package-lock.json
- packages/stellar-payments/package.json
- packages/tron-payments/package-lock.json
- packages/tron-payments/package.json
- tsconfig.build.json
- tsconfig.json
A feature requested for use on the BTMs. Instead of the sender paying the network fee, it gets deducted from the transaction outputs
> [feat] (bitcoin) Support for recipient pays fee

- packages/bitcoin-cash-payments/package-lock.json
- packages/bitcoin-cash-payments/package.json
- packages/bitcoin-payments/package-lock.json
- packages/bitcoin-payments/package.json
- packages/bitcoin-payments/src/bitcoinish/utils.ts
- packages/litecoin-payments/package-lock.json
- packages/litecoin-payments/package.json
- packages/ripple-payments/src/constants.ts
Prerequisite: https://github.com/go-faast/blockbook-client/pull/6
> [fix] (bitcoinish,ripple) Retry request timeouts and only retry twice

- packages/bitcoin-payments/package-lock.json
- packages/bitcoin-payments/package.json
- packages/bitcoin-payments/src/BaseBitcoinPayments.ts
- packages/bitcoin-payments/src/SinglesigBitcoinPayments.ts
- packages/bitcoin-payments/test/e2e.mainnet.test.ts
- packages/bitcoin-payments/test/e2e.testnet.test.ts
This can help prevent situations where
- There was a mistake constructing the PSBT
- A malicious party changes the PSBT (ie MITM or unauthorized database access)
> [fix] (bitcoin) Validate PSBT before signing

- packages/payments-common/src/types.ts
braking change to payments-common for support of utxo tx reprocessing
> [feat] forced utxos

- packages/bitcoin-cash-payments/package-lock.json
- packages/bitcoin-cash-payments/package.json
- packages/bitcoin-cash-payments/test/HdBitcoinCashPayments.test.ts
- packages/bitcoin-cash-payments/test/e2e.mainnet.test.ts
- packages/bitcoin-payments/package-lock.json
- packages/bitcoin-payments/package.json
- packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
- packages/bitcoin-payments/src/bitcoinish/types.ts
- packages/bitcoin-payments/src/bitcoinish/utils.ts
- packages/bitcoin-payments/test/HdBitcoinPayments.test.ts
- packages/bitcoin-payments/test/e2e.mainnet.test.ts
- packages/coin-payments/package-lock.json
- packages/coin-payments/package.json
- packages/ethereum-payments/package-lock.json
- packages/ethereum-payments/package.json
- packages/litecoin-payments/package-lock.json
- packages/litecoin-payments/package.json
- packages/litecoin-payments/test/HdLitecoinPayments.test.ts
- packages/litecoin-payments/test/e2e.mainnet.test.ts
- packages/ripple-payments/package-lock.json
- packages/ripple-payments/package.json
- packages/stellar-payments/package-lock.json
- packages/stellar-payments/package.json
- packages/tron-payments/package-lock.json
- packages/tron-payments/package.json
> [feat] forces utxos

- packages/ethereum-payments/src/EthereumPaymentsUtils.ts
- packages/ethereum-payments/test/EthereumPaymentsUtils.test.ts
> [feat](erc20) allow tokens with no base denom

- packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
> [fix](utxo) include forced utxos in sweep checks

- packages/bitcoin-cash-payments/src/BaseBitcoinCashPayments.ts
- packages/bitcoin-payments/src/BaseBitcoinPayments.ts
- packages/bitcoin-payments/test/e2e.mainnet.test.ts
- packages/doge-payments/src/BaseDogePayments.ts
- packages/ethereum-payments/src/NetworkData.ts
- packages/litecoin-payments/src/BaseLitecoinPayments.ts
When fees go awry, we need to know why
> [fix] (eth,btc,bch,ltc,doge) Log recommended fee rates

- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
- packages/stellar-payments/src/BaseStellarPayments.ts
- packages/stellar-payments/src/constants.ts
- XLM tx needs longer expiration period
- ERC20 shouldn't throw when Transfer event is missing and not executed
> Fix XLM and ERC20 bugs

- packages/bitcoin-payments/src/BaseBitcoinPayments.ts
- packages/bitcoin-payments/src/bitcoinish/BitcoinishBalanceMonitor.ts
- packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
- packages/bitcoin-payments/test/e2e.testnet.test.ts
- packages/payments-common/src/types.ts
- Add new `address` field to `UtxoInfo`
- Add new `scriptPubKeyHex` field to `UtxoInfo`
- Rename `rawTx` to `txHex` in `UtxoInfo`
> [feat] (bitcoinish) Expose utxo script pubkey hex and address

- packages/bitcoin-payments/src/bitcoinish/BitcoinishPaymentsUtils.ts
- packages/bitcoin-payments/test/BitcoinPaymentsUtils.test.ts
- packages/ethereum-payments/src/BaseEthereumPayments.ts
- packages/ethereum-payments/src/EthereumPaymentsUtils.ts
- packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
- packages/ethereum-payments/test/end-to-end.test.ts
- packages/payments-common/src/PaymentsUtils.ts
- packages/ripple-payments/src/BaseRipplePayments.ts
- packages/ripple-payments/src/RipplePaymentsUtils.ts
- packages/ripple-payments/test/RipplePaymentsUtils.test.ts
- packages/stellar-payments/src/StellarPaymentsUtil.ts
- packages/stellar-payments/test/StellarPaymentsUtils.test.ts
- packages/tron-payments/src/BaseTronPayments.ts
- packages/tron-payments/src/TronPaymentsUtils.ts
- packages/tron-payments/test/TronPaymentsUtils.test.ts
New method for retrieving latest ledger/block number
> [feat] (all) Add getCurrentBlockNumber to PaymentsUtils

- packages/bitcoin-payments/src/bitcoinish/BitcoinishBalanceMonitor.ts
- packages/bitcoin-payments/src/bitcoinish/BitcoinishPaymentsUtils.ts
- packages/bitcoin-payments/test/BitcoinPaymentsUtils.test.ts
- packages/bitcoin-payments/test/e2e.testnet.test.ts
- packages/ethereum-payments/src/EthereumPaymentsUtils.ts
- packages/ethereum-payments/test/end-to-end.test.ts
- packages/payments-common/src/BalanceMonitor.ts
- packages/payments-common/src/PaymentsUtils.ts
- packages/payments-common/src/types.ts
- packages/ripple-payments/src/RipplePaymentsUtils.ts
- packages/stellar-payments/src/StellarBalanceMonitor.ts
- packages/stellar-payments/src/StellarConnected.ts
- packages/stellar-payments/src/StellarPaymentsUtil.ts
- packages/tron-payments/src/TronPaymentsUtils.ts
Standardize the getBlock util method as part of the interface for all coins
> [feat] (all) Add getBlock to PaymentsUtils

- README.md
> fix: renamings in main readme

- packages/coinlib-bitcoin-cash/README.md
- packages/coinlib-bitcoin/README.md
- packages/coinlib-doge/README.md
- packages/coinlib-ethereum/README.md
- packages/coinlib-litecoin/README.md
- packages/coinlib-ripple/README.md
- packages/coinlib-stellar/README.md
- packages/coinlib-tron/README.md
- packages/coinlib/README.md
> fix: renamings in readme files

- package.json
- packages/coinlib-bitcoin-cash/package.json
- packages/coinlib-bitcoin/package.json
- packages/coinlib-common/package.json
- packages/coinlib-doge/package.json
- packages/coinlib-ethereum/package.json
- packages/coinlib-litecoin/package.json
- packages/coinlib-ripple/package.json
- packages/coinlib-stellar/package.json
- packages/coinlib-tron/package.json
> feat: public publishing with lerna

- packages/coinlib-bitcoin/src/MultisigBitcoinPayments.ts
> [fix](btc): multi import

- packages/coinlib-doge/test/e2e.mainnet.test.ts
- packages/coinlib-litecoin/test/e2e.mainnet.test.ts
fix bug from-to selection in e2e mainnet test which could (did) drain source account to amount above dust (was already fixed for bch)
> [fix](ltc|doge): FromTo selection

- README.md
- packages/coinlib-bitcoin-cash/README.md
- packages/coinlib-bitcoin/README.md
- packages/coinlib-doge/README.md
- packages/coinlib-ethereum/README.md
- packages/coinlib-litecoin/README.md
- packages/coinlib-ripple/README.md
- packages/coinlib-stellar/README.md
- packages/coinlib-tron/README.md
- packages/coinlib/package.json
> [fix](all) absolure ref in readme for npm view ref support

- packages/coinlib-bitcoin-cash/package-lock.json
- packages/coinlib-common/src/types.ts
- packages/coinlib-doge/package-lock.json
- tsconfig.build.json
- tsconfig.json
Also update tsconfig aliases to reflect new package names
> Switch block info raw type to object

- packages/coinlib-bitcoin/package-lock.json
- packages/coinlib-bitcoin/src/SinglesigBitcoinPayments.ts
- Add useful messages for troubleshooting signing issues
- Add error in case nothing is signed
> [debug] (btc) Improve debug logging of multi-input signing logic

- packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPaymentsUtils.ts
- packages/coinlib-bitcoin/test/fixtures/transactions.ts
Add missing address field to txinfo inputUtxos
> [fix] (bitcoinish) Add missing fields in txInfo.inputUtxos

- packages/coinlib/tsconfig.json
> Tell coinlib how to find our custom types

- packages/coinlib-bitcoin/test/BitcoinPaymentsUtils.test.ts
> remove relative import

- packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
- packages/coinlib-ethereum/src/NetworkData.ts
- packages/coinlib-ethereum/src/NetworkDataBlockbook.ts
- packages/coinlib-ethereum/src/NetworkDataWeb3.ts
- packages/coinlib-ethereum/src/constants.ts
- packages/coinlib-ethereum/src/types.ts
- packages/coinlib-ethereum/test/HdEthereumPayments.test.ts
- packages/coinlib-ethereum/test/erc20/end-to-end.test.ts
- packages/coinlib-ethereum/test/fixtures/mocks.ts
> Fix breaking tests

- packages/coinlib-bitcoin/test/e2e.testnet.test.ts
- packages/coinlib-ripple/test/e2e.test.ts
- packages/coinlib-stellar/test/e2e.test.ts
fix balance activity breaking tests
related to https://github.com/bitaccess/coinlib/pull/302#issuecomment-1163561410
> fix balance activity breaking tests

- README.md
- package-lock.json
- packages/coinlib-bitcoin-cash/package-lock.json
- packages/coinlib-bitcoin-cash/package.json
- packages/coinlib-bitcoin/package-lock.json
- packages/coinlib-bitcoin/package.json
- packages/coinlib-common/package-lock.json
- packages/coinlib-common/package.json
- packages/coinlib-common/src/SharedDependencies.ts
- packages/coinlib-doge/package-lock.json
- packages/coinlib-doge/package.json
- packages/coinlib-ethereum/package-lock.json
- packages/coinlib-ethereum/package.json
- packages/coinlib-ethereum/src/BaseEthereumPayments.ts
- packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts
- packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
- packages/coinlib-ethereum/src/NetworkData.ts
- packages/coinlib-ethereum/src/NetworkDataWeb3.ts
- packages/coinlib-ethereum/src/erc20/BaseErc20Payments.ts
- packages/coinlib-litecoin/package-lock.json
- packages/coinlib-litecoin/package.json
- packages/coinlib-ripple/package-lock.json
- packages/coinlib-ripple/package.json
- packages/coinlib-stellar/package-lock.json
- packages/coinlib-stellar/package.json
- packages/coinlib-tron/package-lock.json
- packages/coinlib-tron/package.json
- packages/coinlib/package-lock.json
- packages/coinlib/package.json
import bignumber from @bitaccess/ts-common
> using bignumber from @bitaccess/ts-common

- packages/coinlib-common/src/types.ts
- packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts
> [GG-84] Refactor coinlib to return `fee` balance activity type

- packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts
we were missing creating balance activity for some erc20 token because we were looking at just `to` and `from` address when retrieving block balance activities.
For example in this block `4008354`,  tx: https://eth1.trezor.io/api/v2/tx/0x8d2559345963925a38791e308acf6b09504a4c6db498a63f9e01a049c35a636b
our address received a token but we failed to track it , I'm guessing this was a token airdrop. because even etherscan did not list this in the address transaction list.
I was able to notice something was off because the reconciliation code had negative balance for the SNT token, and it was the first entry.  block `4008364`, tx: https://eth1.trezor.io/api/v2/tx/0x2dc6863f56179bae96ce6a64241f44fd097397bb2b17d6b84b20f24c5249bdf8. 
Then it clicked that we must have received earlier but we …
> include all involved address in addressTransaction set

- packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts
- packages/coinlib-ethereum/src/types.ts
blockbook-client was wrongly insantiated with an infura node config
> fix config

- packages/coinlib-bitcoin-cash/LICENCE
- packages/coinlib-bitcoin/LICENCE
- packages/coinlib-common/LICENCE
- packages/coinlib-doge/LICENCE
- packages/coinlib-ethereum/LICENCE
- packages/coinlib-litecoin/LICENCE
- packages/coinlib-ripple/LICENCE
- packages/coinlib-stellar/LICENCE
- packages/coinlib-tron/LICENCE
- packages/coinlib/LICENCE
> license: update copyright year

- packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts
> GG-240 skip balance activity for not confirmed tx

- packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts
> GG-240: skip blockhight 0

- packages/coinlib-ethereum/src/utils.ts
> [GG-177] Add EAI_AGAIN error to list of retryable coinlib-ethereum errors

- packages/coinlib-bitcoin/test/fixtures/singlesigTestnet.ts
removed some wrong fixture address from bitcoin testnet test
> (test) [btc] remove some incorrect test payport addresses

- packages/coinlib-doge/test/DogePaymentsFactory.test.ts
- packages/coinlib-doge/test/HdDogePayments.test.ts
- packages/coinlib-doge/test/UHdDogePayments.test.ts
- packages/coinlib-doge/test/e2e.mainnet.multisig.test.ts
- packages/coinlib-doge/test/e2e.mainnet.test.ts
- packages/coinlib-doge/test/helpers.ts
- packages/coinlib-doge/test/utils.ts
> (test) [DOGE] seperate logger by filename

- packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPayments.ts
While trying to find an ideal utxo selection, a fee estimate is performed for every utxo. However this is redundant because the same fee estimate applies to all attempts. Refactor this to precalculate the ideal utxo fee before trying each utxo to reduce the number of duplicate debug messages.
> Reduce fee estimate logging noise

- packages/coinlib-ethereum/src/NetworkDataBlockbook.ts
> [GG-341] return zero balance if address has not token balance

- packages/coinlib-bitcoin-cash/src/BaseBitcoinCashPayments.ts
- packages/coinlib-bitcoin-cash/src/MultisigBitcoinCashPayments.ts
- packages/coinlib-bitcoin-cash/src/SinglesigBitcoinCashPayments.ts
- packages/coinlib-bitcoin/package.json
- packages/coinlib-bitcoin/src/BaseBitcoinPayments.ts
- packages/coinlib-bitcoin/src/KeyPairBitcoinPayments.ts
- packages/coinlib-bitcoin/src/MultisigBitcoinPayments.ts
- packages/coinlib-bitcoin/src/SinglesigBitcoinPayments.ts
- packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPayments.ts
- packages/coinlib-doge/src/BaseDogePayments.ts
- packages/coinlib-doge/src/MultisigDogePayments.ts
- packages/coinlib-doge/src/SinglesigDogePayments.ts
- packages/coinlib-litecoin/src/BaseLitecoinPayments.ts
- packages/coinlib-litecoin/src/HdLitecoinPayments.ts
- packages/coinlib-litecoin/src/KeyPairLitecoinPayments.ts
- packages/coinlib-litecoin/src/MultisigLitecoinPayments.ts
- packages/coinlib-litecoin/src/SinglesigLitecoinPayments.ts
- packages/coinlib-litecoin/src/helpers.ts
Fixes issues caught by tests for previous merge of this branch
> Fix bitcoinish multisig tx size estimate and respect addressType option when deriving addresses

- packages/coinlib-doge/test/e2e.mainnet.multisig.test.ts
- packages/coinlib-doge/test/e2e.mainnet.test.ts
- packages/coinlib-litecoin/src/HdLitecoinPayments.ts
- packages/coinlib-litecoin/src/helpers.ts
> [fix] (ltc) Fix bad relative import

- packages/coinlib-doge/test/e2e.mainnet.multisig.test.ts
- packages/coinlib-litecoin/src/HdLitecoinPayments.ts
- packages/coinlib-litecoin/src/KeyPairLitecoinPayments.ts
> [fix] (ltc) fix getAddress parameter datatype

- packages/coinlib-bitcoin/src/BitcoinPaymentsUtils.ts
- packages/coinlib-bitcoin/src/utils.ts
- packages/coinlib-bitcoin/test/BitcoinPaymentsUtils.test.ts
Support for retrieving fee rates from https://mempool.space/api/v1/fees/recommended
> feat(BIT-1172): support mempool.space fee recommendations

- bin/publish.sh
- bin/version.sh
(Description here)
Prepend lerna command with node modules binary path in publish script and version script.
> ci: lerna script

- bin/buildall.sh
Prefix lerna command in buildall script with node_modules binary path.
> ci: update buidall script

- README.md
- packages/coinlib-bitcoin/src/BitcoinPaymentsUtils.ts
- packages/coinlib-bitcoin/src/bitcoinish/utils.ts
[BIT-3999 Use mempool.space for fee rate recommendation](https://bitcoin-depot.atlassian.net/browse/BIT-3999)
- Add logging
- Update the README
> bit-3999: use-mempool-space-fee part 2

- packages/coinlib-bitcoin/src/BitcoinPaymentsUtils.ts
- packages/coinlib-bitcoin/src/utils.ts
- packages/coinlib-bitcoin/test/BitcoinPaymentsUtils.test.ts
[BIT-4346 Add testnet support for mempool.space fee reco](https://bitcoin-depot.atlassian.net/browse/BIT-4346)
> bit-4346: add testnet support for mempool.space fee reco
