packages/ripple-payments/src/BaseRipplePayments.ts, packages/stellar-payments/src/BaseStellarPayments.ts, packages/tron-payments/src/HdTronPayments.ts
Flipping the lines in the returned object will leak of extended private key as public key will be overwritten by `hdKey` property from config.
Add explicit omission of `hdKey` property to avoid accidental private key exposure
=> [fix] (all) explicit omit of hdKey in PublicConfig

packages/ethereum-payments/src/BaseEthereumPayments.ts
Ethrereum nodes do not throw an error if nonce is too high. Transaction is simply unavailable after transmition
=> [fix] (ethereum) throw appropriate error on nonce too low

packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/test/HdEthereumPayments.test.ts, packages/ethereum-payments/test/fixtures/mocks.ts
* send transaction without waiting for confirmation
* set types to result of getTransactionReceipt
* consistent data return for different getTransactionReceipt results
* add test coverage
=> [fix] (ethereum) fix getTransactionReceipt integration

packages/payments-common/src/types.ts
allow optional return of current head of blockchain in `BaseTransactionInfo`
=> [feature] (common) optional block number in tx info

packages/bitcoin-payments/package-lock.json, packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/HdBitcoinPayments.test.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts, packages/bitcoin-payments/test/e2e.testnet.multisig.test.ts, packages/bitcoin-payments/test/e2e.testnet.test.ts, packages/ethereum-payments/package-lock.json, packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/test/HdEthereumPayments.test.ts, packages/ethereum-payments/test/end-to-end.test.ts, packages/payments-common/src/types.ts, packages/payments-common/test/types.test.ts, packages/ripple-payments/package-lock.json, packages/ripple-payments/src/BaseRipplePayments.ts, packages/ripple-payments/src/RippleBalanceMonitor.ts, packages/ripple-payments/src/constants.ts, packages/ripple-payments/test/e2e.test.ts, packages/stellar-payments/package-lock.json, packages/stellar-payments/src/BaseStellarPayments.ts, packages/stellar-payments/src/StellarBalanceMonitor.ts, packages/stellar-payments/test/e2e.test.ts, packages/tron-payments/package-lock.json, packages/tron-payments/src/BaseTronPayments.ts, packages/tron-payments/src/constants.ts, packages/tron-payments/test/HdTronPayments.test.ts
Currently calling `getBalance` on an unused address will either return a zero balance (BTC, ETH, TRX) or throw an error (XRP, XLM). This PR makes all coins return zero balances when an address is unused.
Summary of changes to `getBalance` result:
- Adjust `confirmedBalance` to no longer deduct the minimum balance and better reflect what it's name implies
- Add `spendableBalance` to convey how much can actually be spent. (ie `confirmedBalance + unconfirmedBalance - minBalance`)
- Add `unactivated` flag to indicate that an address has not yet received the minimum balance needed to be activated (XRP and XLM)
=> Standardize getBalance behaviour for unused addresses

package-lock.json, packages/ethereum-payments/package-lock.json, packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/EthereumPaymentsUtils.ts, packages/ethereum-payments/test/EthereumPaymentsUtils.test.ts, packages/payments-common/src/utils.ts
I think it would also be better to remove and not use `toBaseDenominationNumber`
Description
=> [fix] (common) prohibit fractual base denomination

packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/test/erc20/end-to-end.test.ts
I think that chances that eth to wei conversion will change are quite low so using hardcoded constant here
=> [feat](erc20) use eth const denomination for tx fee

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts
A couple of blockbook nodes have been returning `0xFFFFFFFF` for confirmations count.
See: https://btc5.trezor.io/api/tx/7d16430cae2b10b30768690769ce79b58f88f1a9c4a5bf3cefde4c6207933809
Same result for btc4, but not for btc1, btc2, and btc3
=> [fix] (bitcoin) Handle invalid confirmations count

packages/ethereum-payments/src/BaseEthereumPayments.ts
It appears that `e.message` is actually equal to `"Returned error: nonce too low"` and the current condition is insufficient
=> [fix] (ethereum) Correctly detect nonce too low errors

packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/src/types.ts, packages/ethereum-payments/test/HdEthereumPayments.test.ts
Fixes the following error seen when querying for a tx hash that doesn't have 0x prefix
`invalid argument 0: json: cannot unmarshal hex string without 0x prefix into Go value of type common.Hash`
And eliminates the following gringotts warning about seeing an empty string txid
`Adjusting externalId from  to b58f`
=> [fix] (ethereum) Prefix signed tx id with 0x and return null for unsigned

packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/EthereumPaymentsUtils.ts, packages/ethereum-payments/src/KeyPairEthereumPayments.ts, packages/ethereum-payments/src/bip44.ts, packages/ethereum-payments/test/EthereumPaymentsUtils.test.ts, packages/ethereum-payments/test/HdEthereumPayments.test.ts, packages/ethereum-payments/test/NetworkData.test.ts, packages/ethereum-payments/test/erc20/end-to-end.test.ts, packages/ethereum-payments/test/fixtures/accounts.ts, packages/ethereum-payments/test/fixtures/mocks.ts
* fix tests for nonce
* force lowercase in http mocks (web3 sends addresses out as lowercased)
=> [fix] (eth|erc20) use checksummed addresses only

bin/buildall.sh, packages/ethereum-payments/package-lock.json, packages/ethereum-payments/package.json, packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/HdEthereumPayments.ts, packages/ethereum-payments/src/NetworkData.ts, packages/ethereum-payments/src/constants.ts, packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/src/erc20/HdErc20Payments.ts, packages/ethereum-payments/src/types.ts, packages/ethereum-payments/test/end-to-end.test.ts, tsconfig.json
- Allowing web3 to be passed into config fixes the memory leak issue we've been seeing. Each instance of Web3 appears to leak around 112kB of non-heap memory. Treating it as a singleton by passing in an existing web3 instance provides a solution
- Adds support for websocket providers
- Upgrades to most recent dependencies for many libraries
=> [feat] Support web3 websocket provider and passing web3 in via config

packages/ethereum-payments/package-lock.json, packages/ethereum-payments/package.json, packages/ethereum-payments/src/@types/web3-eth-contract/index.d.ts, packages/ethereum-payments/src/erc20/BaseErc20Payments.ts
Both web3 1.x and 2.x have a feature that supports changing the provider of all instantiated contracts using a single call to the web3.setProvider. To accomplish this a reference to every contract is retained by web3 when using `new web.eth.Contract` which on long running processes (ie a web server) will eventually lead to an OOM error. However, we can work around this by using the `web3-eth-contract` directly so that web3 doesn't retain the reference.
In this PR I also had to add augment type declarations because the provided ones were incomplete (`setProvider` was missing and the `Contract` class was not declared as the default export despite being so)
Fixes this relevant issue: https://github.com/ethereum/web3.js/issues/3042
=> Fix web3 contract closure leak

packages/ethereum-payments/src/constants.ts
Not sure how these where originally determined but they're definitely too high
=> [fix] Lower ERC20 gas limit maximums

packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/src/erc20/HdErc20Payments.ts, packages/ethereum-payments/test/erc20/end-to-end.test.ts, packages/payments-common/src/types.ts
Include a new optional `signerAddress` field in `Payport` type. `getPayport` will use it to return the address responsible for signing transactions for the payport, when different from `address`.
Also refactored some of the create2 methods:
- Add `getAddressSalt` instead of `getXpub` to separate HD derivation responsibility from BaseErc20Payments
- Remove `masterAddress` param from `getPayport` to conform to the global API
=> Return signerAddress in getPayport and refactor create2 address methods

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts
In some cases where a single utxo can be selected to cover the entire transaction the incorrect minimum was being used. This resulted in the fee being subtracted from the output of a transaction without `recipientPaysFee` enabled.
=> [fix] (bitcoin) Fix ideal utxo selection bug

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts
This caused some ideal solution transactions to be considered as sweeps and their fee deducted from the output when they shouldn't be.
Also, fix the neededSat value in the non-ideal solution case. Forgot that in the previous PR
=> [fix] (bitcoin) Only consider payment txs with useAllUtxos as sweeps

packages/ethereum-payments/test/NetworkData.test.ts
The following tests are failing due to what appears to be mismatched address case. Making them all lowercase has them passing again.
```
● NetworkData › getNetworkData default flow
expect(received).toEqual(expected) // deep equality
- Expected  - 1
+ Received  + 1
Object {
"amountOfGas": "21000",
-   "nonce": "27",
+   "nonce": "26",
"pricePerGasUnit": "1000000000",
}
46 |     const res = await networkData.getNetworkData('ETHEREUM_TRANSFER', FeeLevel.Low, from, to)
47 |
> 48 |     expect(res).toEqual({
|                 ^
49 |       'pricePerGasUnit': '1000000000',
50 |       'amountOfGas': '21000',
51 |       'nonce': '27',
at Object.<anonymous> (test/NetworkData.test.ts:48:17)
at runMicrotasks (<anonymous>)
● NetworkData › getNetworkData gas limit multiplier …
```
=> [test] (ethereum) Fix NetworkData tests not mocking nonce requests due to mismatched case

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/src/bitcoinish/types.ts
Problem: When recipientPaysFee is enabled the fee gets deducted from the outputs. However, the first fee estimate is always an upper bound because it assumes the maximum number of change outputs are added. During change handling, some change outputs get dropped due to being too small and the fee has to be reduced. This PR fixes this by modifying the change handling code to increase the outputs by the corresponding amount the fee was reduced by. It does this through a new helper called `adjustTxFee` and is itself also refactored into it's own method called `allocateChangeOutputs`.
In order to support this change, and to improve modularity and code readability, a new object type called `TxBuildContext` was added to contain all the necessary information that must be passed around when …
=> [fix] (bitcoin) Account for recipientPaysFee during fee adjustments in change handling

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts
I happened to notice the network imposed minimum output amount wasn't being enforced when building the payment tx
=> [fix] (bitcoinish) Enforce dust threshold on external outputs

packages/payments-common/src/BasePayments.ts, packages/ripple-payments/src/BaseRipplePayments.ts, packages/ripple-payments/test/e2e.test.ts
The `initAccounts` method was added as a temporary workaround to get the correct settings configured on the deposit address. Now that we have a "service transaction" concept it can be used instead during an initialization step.
=> [feat] (ripple) Deprecate initAccounts for createServiceTransaction

packages/bitcoin-cash-payments/src/BaseBitcoinCashPayments.ts, packages/bitcoin-payments/src/BaseBitcoinPayments.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts, packages/litecoin-payments/src/BaseLitecoinPayments.ts, packages/litecoin-payments/test/e2e.mainnet.test.ts
Hardcoded default fee rates lead to stuck or overpaid transactions. Throw when blockcypher fails so it can be retried later
=> [fix] (bitcoinish) Throw on fee estimate failure instead of using default

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/e2e.mainnet.test.ts
When attempting to sweep an address with dust input utxos, the external output amount total doesn't match up with the filtered input total resulting in incorrect output amounts and an error. This must be merged before 3.0.0 goes live
TODO: add test
=> Fix sweeping when dust utxos are filtered

packages/bitcoin-payments/src/BaseBitcoinPayments.ts
The address at `fromIndex` doesn't match `fromAddress` for all multisig transactions or singlesig transactions that are using a different address type. Additionally, this function is meant to be validating that the PSBT is consistent with the tx object, not that the tx is consistent with itself. For those reasons it makes the most sense to just remove this altogether
=> Remove tx fromAddress validation incompatible with multisig

common/testUtils.ts, packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/test/HdBitcoinPayments.test.ts
This is a hotfix for a production bug that affects transactions where the amount of change is not evenly divisible across the multiple change outputs ("loose change") and gets mistakenly deducted from the output twice. This in and of itself is not particularly concerning because it's just a negligible rounding error. However the new signing validation logic complains and refuses to sign transactions when a few satoshis are misallocated resulting in stuck production transactions.
The few satoshis of leftover change that can't be evenly allocated used to just be added onto the fee. However when recipient pays fee is enabled this would also deduct the output amount by that amount. This results in an output amount that's a few satoshis lower than it should be, and a total reported fee that's …
=> Fix loose change allocation when recipient pays fee

packages/bitcoin-payments/src/BaseBitcoinPayments.ts, packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/src/bitcoinish/types.ts, packages/bitcoin-payments/src/bitcoinish/utils.ts, packages/bitcoin-payments/test/HdBitcoinPayments.test.ts
Also add some extra logging and validation to help catch any tx building bugs.
Also includes important fix for loose change allocation after dynamic fee is recalculated when change outputs are dropped. There was an incorrect assumption that a fee reduction means more loose change to allocate. However that is only the case when the recipient isn't paying for the fee. When they are their output total increases and the total/loose change should remain unchanged.
=> [fix] (bitcoinish) Reduce frequency of loose change by deducting from total weight

packages/bitcoin-payments/src/bitcoinish/utils.ts, packages/ethereum-payments/package-lock.json, packages/ethereum-payments/package.json, packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/NetworkData.ts, packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/src/utils.ts, packages/tron-payments/package-lock.json, packages/tron-payments/package.json, packages/tron-payments/src/BaseTronPayments.ts
I'm seeing an increased number of failed requests as of late. Retries should help with this
- Bitcoin: recognize more types of timeout errors
- Ethereum: Add retries on failed requests
- Tron: Add retries on failed requests
=> Add retries for common request errors

packages/ethereum-payments/package-lock.json, packages/ethereum-payments/package.json
Tests were failing with
```
end to end tests › HD payments › Deriving and Deploying DepositAddress payments
@faast/ethereum-payments:     Ethereum broadcast tx unsuccessful: 0x74fa1e25fc761d438485cb747a28b577035c2991630ccf2e80aec5a58b524b21 Invalid JSON RPC response: ""
```
This [comment](https://github.com/ethereum/web3.js/issues/1470#issuecomment-701879446) suggested upgrading web3 and that fixed the issue
=> [deps] (ethereum) Upgrade web3 to 1.3

packages/bitcoin-cash-payments/package-lock.json, packages/ripple-payments/package-lock.json, packages/ripple-payments/package.json, packages/ripple-payments/src/BaseRipplePayments.ts
Sometimes ripple broadcast (submit) takes a long time (ie 60 seconds). I think this is because it has internal retries that wait for the transaction to complete. There's a new `failHard` flag you can enable when submitting to disable this feature which will hopefully fix some timeouts we're seeing.
Also, GitHub reported a [vulnerability](https://github.com/go-faast/coin-payments/network/alert/packages/ripple-payments/package-lock.json/elliptic/open) in elliptic so the ripple-lib and bip32 upgrades resolve that.
=> Upgrade ripple-lib to 1.9 and enable failHard on submit

packages/ethereum-payments/src/BaseEthereumPayments.ts, packages/ethereum-payments/src/EthereumPaymentsUtils.ts, packages/ethereum-payments/src/constants.ts, packages/ethereum-payments/src/erc20/BaseErc20Payments.ts, packages/ethereum-payments/src/types.ts, packages/ethereum-payments/test/HdEthereumPayments.test.ts, packages/ethereum-payments/test/NetworkData.test.ts, packages/ethereum-payments/test/fixtures/mocks.ts
- Fix getTransactionInfo throwing confusing error: `Cannot read property 'input' of null` when tx is not known to node
- Stop checking gas price during balance requests because it's going to get us rate limited
- Gracefully handle web3 `already known` broadcast error
- Broadcast transactions to blockbook node as backup measure
=> Assorted eth/erc20 fixes

packages/doge-payments/package-lock.json, packages/doge-payments/package.json, packages/doge-payments/test/e2e.mainnet.test.ts
DOGE transactions spending utxos from txs with very large valued outputs (>90M sat) will fail because they exceed javascripts 53-bit number precision. The bitcoinjs-lib verifuint function will throw a `RangeError: value out of range` to try to warn against this problem. We forked bitcoinjs and removed that maximum which could be problematic if we ever wanted to spend from an output that large. Fortunately we don't forsee owning that much DOGE so this will not affect transactions we actually build.
=> Fix doge range error

packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/src/bitcoinish/types.ts
- Additional change outputs were not being generated when dust utxos existed resulting in low wallet throughput
- Refactored some of the other build context utxo fields for clarity
=> Use non-dust utxo count for change count calculation

packages/bitcoin-cash-payments/src/BaseBitcoinCashPayments.ts, packages/bitcoin-payments/src/BaseBitcoinPayments.ts, packages/bitcoin-payments/src/bitcoinish/BitcoinishPayments.ts, packages/bitcoin-payments/src/bitcoinish/utils.ts, packages/bitcoin-payments/test/HdBitcoinPayments.test.ts, packages/doge-payments/src/BaseDogePayments.ts, packages/litecoin-payments/src/BaseLitecoinPayments.ts
The `estimateTxSize` method falsely assumed that each address would have at most one output, since that'd be the most fee efficient way to create a tx. However sometimes creating extra outputs for the same address is desired and that wasn't being accounted for when estimating the size. This resulted in underspending on the fee and confirmation delays.
=> [fix] (bitcoinish) Correctly estimate tx size when an address has multiple outputs

packages/bitcoin-payments/package-lock.json, packages/bitcoin-payments/package.json, packages/bitcoin-payments/src/bitcoinish/BitcoinishBalanceMonitor.ts, packages/bitcoin-payments/test/e2e.testnet.test.ts, packages/payments-common/src/BalanceMonitor.ts, packages/payments-common/src/types.ts
3 new optional `BalanceMonitor` methods currently only implemented in BitcoinishBalanceMonitor
- `subscribeNewBlock` - subscribe to new confirmed block hashes
- `onNewBlock` - Set a callback for all new block events
- `retrieveBlockBalanceActivities` - Retrieve balance activities for a certain block and a given address filter
=> [feat] (bitoinish,common) Support for block balance activity listening

packages/coinlib-bitcoin/src/bitcoinish/BitcoinishBalanceMonitor.ts, packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPaymentsUtils.ts
- If an http request times out while retrieving block data inside `retrieveBlockBalanceActivities` the error is thrown immediately without retries
- Retrying the entire method call would cause redundant iterations over other successful block pages
- The `getBlock` method itself should retry just like many other api calls we make to reduce the likelihood of a request error propagating up to the caller
- This PR also refactors some of the getBlock usage throughout the balance monitor class, primarily naming and using `utils.getBlock` instead of `getApi().getBlockInfo()`
=> [fix] (bitcoinish) Add getBlock retries and refactor associated usage

packages/coinlib-ethereum/src/BaseEthereumPayments.ts, packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts, packages/coinlib-ethereum/test/HdEthereumPayments.test.ts, packages/coinlib-ripple/src/BaseRipplePayments.ts, packages/coinlib-stellar/src/BaseStellarPayments.ts, packages/coinlib-tron/src/BaseTronPayments.ts, packages/coinlib-tron/src/TronPaymentsUtils.ts, packages/coinlib-tron/test/HdTronPayments.test.ts
resolvePayport was incorrectly throwing an error when a valid payport was provided that also included an index (and other misc fields)
=> [fix] (eth,trx,xlm,xrp) resolvePayport should not throw when valid and includes index

package-lock.json, package.json, packages/coinlib-bitcoin-cash/src/BaseBitcoinCashPayments.ts, packages/coinlib-bitcoin-cash/test/e2e.mainnet.test.ts, packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPayments.ts, packages/coinlib-bitcoin/src/bitcoinish/types.ts, packages/coinlib-bitcoin/test/e2e.testnet.multisig.test.ts, packages/coinlib-common/src/types.ts, packages/coinlib-ethereum/test/end-to-end.test.ts, packages/coinlib-ethereum/test/erc20/end-to-end.test.ts, packages/coinlib-ripple/test/e2e.test.ts, packages/coinlib-tron/test/HdTronPayments.test.ts, tsconfig.build.json, tsconfig.json
Raw transaction data sizes can become very large when many input utxos are involved. This PR adds a new `lookupTxDataByHash` create transaction option to facilitate looking up utxo `txHex` asynchronously instead of requiring it to be provided in every utxo. This will reduce the serialized tx and utxo sizes resulting in better performance, particularly for large batch transactions.
=> [feat] Support async tx data hex lookup callback when creating transactions

packages/coinlib-ethereum/src/erc20/BaseErc20Payments.ts
eth block timestamps are measured in seconds but nodejs Date expects ms
=> Fix erc20 tx info timestamp

packages/coinlib-bitcoin/src/bitcoinish/BitcoinishBalanceMonitor.ts, packages/coinlib-common/src/BalanceMonitor.ts, packages/coinlib-common/src/types.ts, packages/coinlib-ethereum/src/EthereumBalanceMonitor.ts, packages/coinlib-ripple/src/RippleBalanceMonitor.ts, packages/coinlib-stellar/src/StellarBalanceMonitor.ts
- change the `txToBalanceActivity` method on the base`BalanceMonitor` interface to only return an `BalanceActivity[]`, so this change further cascaded down into the BalanceMonitor implementation for all our supported coins.
- tweak the `txToBalanceActivity` method on the `EthereumBalanceMonitor` to
i. reflect a net change in the address i.e includes fees in the balance activity amount
ii. use the correct sign for the amount, `out` type activies should be `negative`, `in` should be positive.  
the other changes are auto-formatting changes.
=> Return array of balance activities

packages/coinlib-common/src/BasePayments.ts, packages/coinlib-common/src/PaymentsUtils.ts, packages/coinlib-common/src/types.ts, packages/coinlib-common/src/utils.ts
Some bignumber related types in coinlib-common was still from @faast/ts-common, which caused type inconsistency.
This pr removed all @faast/ts-common uses from coinlib-common.
=> GG-74 replace all @faast/ts-common to @bitaccess/ts-common in coinlib-common

bin/build.sh, package.json
When attempting to fix the broken builds, I eliminated the ts-config build script dependency and replaced it with just a tsc call. However this library also uses rollup so the build "succeeded", but was missing some artifacts because rollup never ran. That's why libraries depending on 6.0.3 cannot import the module, the .cjs.js files were missing.
Supersedes https://github.com/bitaccess/coinlib/pull/311
=> Add missing rollup step to build script

packages/coinlib-ethereum/src/BaseEthereumPayments.ts, packages/coinlib-ethereum/src/EthereumPaymentsUtils.ts, packages/coinlib-ethereum/src/HdEthereumPayments.ts, packages/coinlib-ethereum/src/NetworkData.ts, packages/coinlib-ethereum/src/NetworkDataBlockbook.ts, packages/coinlib-ethereum/src/NetworkDataWeb3.ts, packages/coinlib-ethereum/src/UnitConvertersUtil.ts, packages/coinlib-ethereum/src/bip44.ts, packages/coinlib-ethereum/src/constants.ts, packages/coinlib-ethereum/src/erc20/BaseErc20Payments.ts, packages/coinlib-ethereum/src/erc20/HdErc20Payments.ts, packages/coinlib-ethereum/src/erc20/utils.ts, packages/coinlib-ethereum/src/types.ts, packages/coinlib-ethereum/src/utils.ts, packages/coinlib-ethereum/test/EthereumPaymentsFactory.test.ts, packages/coinlib-ethereum/test/HdEthereumPayments.test.ts, packages/coinlib-ethereum/test/NetworkData.test.ts, packages/coinlib-ethereum/test/erc20/end-to-end.test.ts, packages/coinlib-ethereum/test/fixtures/mocks.ts
In order to support Ethereum layer 2's (ie optimism, arbitrum) and alternative EVM chains (ie BSC, RSK) we need to allow the coinlib-ethereum classes to be instantiated with custom network constants. In particular an alternative `chainId` and `derivationPath` is typically needed, in addition to allow customization of the name/symbol/decimals of the native coin.
This change adds a new optional `networkConstants` field to the config objects so that all the exact same classes and logic can be shared across all chains. Additionally, both `HdEthereumPayments` and `HdErc20Payments` now support a `derivationPath` config option to enable user-specified overriding of the derivation path.
=> [feat] (ethereum) Support custom network constants for L2/alt EVM chains

packages/coinlib-common/src/HdKeyUtils.ts, packages/coinlib-common/test/HdKeyUtils.test.ts
If an xpub with depth 5 is passed into the deriveHDNode function and a path is provided that itself is shorter than depth 5, throw an error because that's a sign that an incorrect derivation path was specified that doesn't actually match the xpub. The path should always have equal or more parts than the base key that's going to be derived.
=> Throw error when deriving hd key to shallow path

packages/coinlib-bitcoin/src/bitcoinish/BitcoinishPayments.ts, packages/coinlib-bitcoin/test/e2e.testnet.test.ts, packages/coinlib-bitcoin/test/fixtures/singlesigTestnet.ts
- [test] (btc) Fix end to end multi-input test fixtures
- [fix] (btc) Add one sat to min relay fee estimate to avoid too low rejection
=> [GG-241] Fix min relay fee off by 1 sat, repair broken multi-input fixtures

packages/coinlib-ethereum/src/NetworkData.ts
The `includeTransactionObjects` argument was not being passed to the functions that resolves the blockbook/web3 calls. This caused  the api to return block data without transactions objects which in turn affects the balance monitor for ETH, causing it not to find the address involved in  transactions inside the block.
=> [GG-336] pass down [includeTransactionObjects] argument

packages/coinlib-litecoin/test/e2e.mainnet.test.ts, packages/coinlib/src/CoinPayments.ts, packages/coinlib/src/types.ts, packages/coinlib/test/CoinPayments.test.ts
The old way to get `AnyPayments` instance is to build it in `CoinPayments` constructor and store them in the `CoinPayments` object and later use `forNetwork` method to get the pre-defined payments config combined with the overriding config and build another one. The first build in the CoinPayments constructor is unnecessary for our `GringottsSeedSignerClient`. 
This pr adds a method `getSpecificPayments` to allow users to get any payment instance directly from an 'empty' CoinPayments(aka seedCoinPayments) without pre-building anyPayments in `CoinPayments` constructor.
=> add getSpecificPayments to CoinPayments

package.json, packages/coinlib-bitcoin/src/BitcoinPaymentsUtils.ts, packages/coinlib-bitcoin/test/BitcoinPaymentsUtils.test.ts, packages/coinlib-bitcoin/test/e2e.mainnet.test.ts, packages/coinlib-bitcoin/test/e2e.testnet.multisig.test.ts, packages/coinlib-bitcoin/test/e2e.testnet.test.ts, packages/coinlib-types/src/constants.ts, packages/coinlib-types/src/types.ts, packages/coinlib/test/CoinPayments.test.ts
[BIT-3999 Use mempool.space to get fee reco when doing transactions and fee bumps](https://bitcoin-depot.atlassian.net/browse/BIT-3999)
- **use mempool.space fee reco with fallback**
- **restrict test command to bitcoin related tests**
- **fix typescript error**
- **sort list of supported network symbols**
- **configure broken tests to be skipped if key not supplied**
- **extend test coverage to getting fee reco from mempool.space**
- **add test case: fee reco should fall back to blockbook if mempool.space fails**
=> bit-3999: use mempool.space fee reco
